apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: fmahdi09/bff:0.11.5
          envFrom:
            - configMapRef:
                name: bff-config
          env:
            - name: Database__Port
              valueFrom:
                secretKeyRef:
                  name: cnpg-cluster-app
                  key: port
            - name: Database__Username
              valueFrom:
                secretKeyRef:
                  name: cnpg-cluster-app
                  key: username
            - name: Database__Password
              valueFrom:
                secretKeyRef:
                  name: cnpg-cluster-app
                  key: password
            - name: Duende__LicenseKey
              valueFrom:
                secretKeyRef:
                  name: duende-license-key
                  key: key
            - name: Identity__Secret
              valueFrom:
                secretKeyRef:
                  name: client-secret
                  key: secret
