---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-secret
  namespace: bff
spec:
  encryptedData:
    secret: AgCmk7B8sdOsl/05pcO2EuFF2GXgG2Ftcu7+0YUNJ+9QCo+a+jWLv5raTtOiYr7eQxR1TeSpFLVV1ViLMvtt+Cw2I7+H/pMnLatnKWYOPdsdfwdzHR79VJ60TZkkTyhxlBH6NZYiSbBX30tiWCzshZ6pkZNvceXmgbyDkmZPlTwEOR379GksPMDZ1lwZ3qSBMaE/GP8xNwgilLiKNilSIpJg1KocHTvmT6ciGIsS9/PcoujWX8KEpOQYm03eh/DCZj0F1IIi0NwLGqrpNmLpJQhumBeuQtFhMvffAa0kNbALN5BAX3wpHRN5GV/uVS8Z4KMsDD2Z00WYk2YaJXAKtjq6Tb7iX4YaKOxyFibVZ0oSgMC1I3KrPsezIXNzgsVt3mOWadbkN8xnT9t5+CoMnFQ06kNe2HezdTJF7Vr+uo3Q1Xzcwo/xmcjGuycTHCL0J/ecE32WVbLpVriJjjRLgIXMBLrrAzObkycLCPJGUayhdo4HwSNH4YMMTwmHJdpjUZfDkDJNKXlCDk29kNr7PPzjJhMp3kmXVpkQiN8ZsCUQeL7mOVCpgogTmj9NX4FiQ2HDCyUP54oBI4rqdlcxaOoMwoCGFnhW07eboOSQGsa9cdpoB1zEwsz3is0ZklYsm6pwOQEgUBKMCwK41oqL58zCnGJWj9aEmznfYppskqsapD3qLyh1X6svUDla05D6flEMz4Saf1r8XeNbuR2qI3gAqv/9s3WtIDXyKveiLIJwjfgeAyxYLcODkk2ABw==
  template:
    metadata:
      name: client-secret
      namespace: bff
