---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgDTJISwJUIbbFZs7PzNiZpEPlR9hNmQkAy4fJTwWkvS7gGW4oDLcW1AYScQrUvmirO/xoJfiV+QN6G1/NRNmD5w7sRdaAix4x/XHNH6ADTJuq1I8dKy7SEA0ox7gOiSQnXR6Uc7tIbvT87OE8ELwKnZFojUCVaZN4Uva6sCzbl7P07UkrYM4i9qbQa0B9s4QCCtZ6Y37LeBW1Ue1aZLeWL1LM417BFBk14hGcYY/x3sHByzmAryLdAsL/4RPq6K/WHTrxjsyh8aKc8SBvhWxBmTkWIuHkhkZdKCDbntolYL0khGdh0cWooEeqoDZq+/tn2RB4XY3R3oYmXOoEeVfWIwzlt2/e9/VehtXB30bAFIqnBLVIFwmdhd2sxBS4TC4ncZ1fyCY9YyTpU2ukw4baJPRVvA7r2LAWUCwng1CHdJDFHp64k9rWfBIippTGtrUgCcMvZjRsFKfz5pUTTXNia282qz0R+WlTL9XEKhkJNO2JehSftDtaaLOHTSBaz/QVbsKkHTcAmfhvoZ7bxPZgDQDQD9xNmYrjQ4p7erFqvBxgYzttsRh4iyeXqszRupA+VGLy/K7ti6xxaeEMLITbc1R3g4Mg56I5gUWHIxa5VkQN2bkecjq1CTnbbORlnJGjJ44Wg2n64bKfSaW/zzbCjAQiddEzYMsrlaPm4cly15C4rYrBu1ynpvOVpZP8CzYREVKP6N1FzXhlfsyK7Iru+1ZdV8DzX1geIhlm0EMcMuB/K9JQvT2LBhUBO9sn5nG2k+T21Aua4YDuBu5SVuq+R7MrHqBEEI2TSyhvyqoe5wd1gyKwv5uanfM/aR/3lmofrYoealOlvBMd+wusO4U/7yxSwZrLB3UKAlOdwAQypL8Y+vlGd2EPDmnWibPrsnOGrgDHuNPLF6PupJzoXQ66cMoxkHooMbtQZdsrfZlg/m
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflared
