apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/Tikal-online/tikal-infrastructure.git
    targetRevision: main
    path: infrastructure/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true