---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: monitoring
spec:
  encryptedData:
    password: AgAxrLjQCJOAL1yByTT7pzH9Y0/RxWgOpE1tFT9xuUDvlTXdec8Y7TDyLXtSlBaqj/98upcOd4gXT2pLm2zwvMB3zTStObAdGvF6XU2bkwNnOWM7laUpTzoPOLvHD40zPVo0XXW4okT20v5fgQV6Y4KYr+lR2hnpnF3zUvZNjv4NEp1MclnzwfpEGByzx7uXYJLMcxX638dEHCin1/iFUwzF1rQlKXylsdC5kLGTMF4kU+aXqVHAvXLDNz7WlhtYWJDJoMFwG7q5MvnlK94vqqoj07yeMRZPECMNEfv/WSU3qHrV7WkNSTOcUx7b3UQZWdsF/ppI3awwiDmC3N9EHEu3L7N/GawnzV/u3U/B7TPpGYtnq8+9oUCMMC7wrkm0tkEjh42PqhT/0icYSeOAYuwqMZMXP3C9myLaytRIIsDNnXMiwAquKBLmVKo8NLdvmMs/oLWrTgeS3vLlE8MSMz/7nAfRanIk5uVkf2U8k4kKGCd62JxgS+sMXAQBeS2bML+cRAnJGi/EIiOSitXNFM0LNq+ujO++Onq5nkgmZJ2qaU8py04RpsrJ+CS3ePRIPvBHUYK7EEOYzsWBrJ0pTzfAEIQqxISt6xWBupvDSlFw4PxVOnscx6iMMZKnYrXNc2ieB7PvNfV7TD+JxspslY1BqDtkzSQTk550fOxH9iuO05lR/3zqwxxROZRpuVNmNW9C7MdZCRmjlWzwax25YhvWY+qHXqHF6CI6oPKUiCrzBJej+Vp2IPem5U0dyfDAuGNpr6w1Ug3evZZziFsW/uIGmVchHNwRGPdcdkuePRjdtDL04/8n3mcDI01xwRqlCmG15HcNXqa9L3z8QMRXPoM/hD6kfABu0Ia8NGeSe8sXJob8zNtDBVpJbj6WpkL/GO59hxXReaVj80+gx3YTomx5DuJQAytpyuIl64Xg
  template:
    metadata:
      name: grafana-credentials
      namespace: monitoring
