apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: identity
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Tikal-online/tikal-infrastructure.git
    targetRevision: main
    path: app/identity
  destination:
    server: https://kubernetes.default.svc
    namespace: identity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true