apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-k8s-monitoring
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: k8s-monitoring
    targetRevision: ^4
    helm:
      releaseName: grafana-k8s-monitoring
      valuesObject:
        cluster:
          name: my-cluster
        destinations:
          grafana-cloud-metrics:
            type: prometheus
            url: https://prometheus-prod-65-prod-eu-west-2.grafana.net./api/prom/push
            auth:
              type: basic
              username: "2817479"
              password: glc_eyJvIjoiMTU5NzA3NCIsIm4iOiJzdGFjay0xNDQ2NjIzLWludGVncmF0aW9uLWRlbGV0ZXRoaXMtdGVzdCIsImsiOiIwOFRyOFM5bkxQNmxmMEd1M0VEMTBGM0kiLCJtIjp7InIiOiJwcm9kLWV1LXdlc3QtMiJ9fQ==
          grafana-cloud-logs:
            type: loki
            url: https://logs-prod-012.grafana.net./loki/api/v1/push
            auth:
              type: basic
              username: "1404416"
              passwordKey: password
            secret:
              create: false
              name: grafana-credentials
              namespace: monitoring
        clusterMetrics:
          enabled: true
          collector: alloy-metrics
        hostMetrics:
          enabled: true
          collector: alloy-metrics
          linuxHosts:
            enabled: true
          windowsHosts:
            enabled: true
          energyMetrics:
            enabled: true
        clusterEvents:
          enabled: true
          collector: alloy-singleton
        collectors:
          alloy-metrics:
            presets:
              - clustered
              - statefulset
          alloy-singleton:
            presets:
              - singleton
        collectorCommon:
          alloy:
            remoteConfig:
              enabled: true
              url: https://fleet-management-prod-011.grafana.net
              auth:
                type: basic
                username: "1446623"
                passwordKey: password
              secret:
                create: false
                name: grafana-credentials
                namespace: monitoring
        telemetryServices:
          kube-state-metrics:
            deploy: true
          node-exporter:
            deploy: true
          windows-exporter:
            deploy: true
          kepler:
            deploy: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
