apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-config
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Client__BffUrl: "https://api.tikalonline.com"
  Client__BackendUrl: "http://tikal-backend.tikal-backend.svc.cluster.local"
  Database__DatabaseName: "identity"
  Database__Host: "cnpg-cluster-rw.cnpg-cluster.svc.cluster.local"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://grafana-k8s-monitoring-alloy-receiver.monitoring.svc.cluster.local:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"