---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-secret
  namespace: identity
spec:
  encryptedData:
    secret: AgDNM9Uk4ZugOsYUomURU4ViNtsv6K6xhcVvsgI6l8qtKqqZoAfZz9DKM7inHA5Ot2fgEpJz4aMsnSV+hQBPpXy8SK0ticze8WvzEKyyfGUTPsV/XbNKii5Pl9qh1plFNDCthqddNezlCKGiFWecJQPTe+/IXorq88aeUVZxmKWwM79gkr6rLgkjofTBCSTu9Oyd6iqaJh2s63cogce4Owf/cBTSexfnaO2b9rf91r6fmM2uM2/fUZd4qUedhZhhLByxP3UQ4dU0uskIr0SGVVekp1E13Zkk4+qA5jyGgHGiDAx5gVTZvVavXsaH0ELOrprrtyaUXrjriknDs816rSY1lwYn6ng88QOTSUeWbiWfRfHKZRP438BPDmNMUlph/Dh790Y1nXFXmbmcndnjLvfVPAzKae+ZlgmQ0ibuZnYUmdgNzoF73BbDDomkj+D5NBUYXJ+eYZ76HJAIG9MfyNXLcMmwxaazB+siqVcbGKMp7xuKPUUGwNOpQbD3tmZ3xkOr94xz3+MOQDbpdWhN1b7DYK+vKr3ECDcbHGr1d08sEQZ42blvEsMJxt2wwBdaYMdkF986pJwRxOcArL2sh2rnKDzPcyIUv7zNfusighf/yp+W7IWG1XM0LcB6S3l2BsCTlSL200W4ApZuj1rKYT/pqKGKN5Hgb6hbxxogg08+IBRkgPq7olgPo0Igd9JGII55KR3xuEYsVaWKQv91YtOp/jdqmKGIJEe4aTj+VghPB+yqXYsGR4484Th/sg==
  template:
    metadata:
      name: client-secret
      namespace: identity
