apiVersion: batch/v1
kind: Job
metadata:
  name: tikal-backend-migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: fmahdi09/tikal-backend:0.36.0
          args: ["migrate"]
          envFrom:
            - configMapRef:
                name: tikal-backend-config
          env:
            - name: Database__Port
              valueFrom:
                secretKeyRef:
                  name: cnpg-cluster-app
                  key: port
            - name: Database__Username
              valueFrom:
                secretKeyRef:
                  name: cnpg-cluster-app
                  key: username
            - name: Database__Password
              valueFrom:
                secretKeyRef:
                  name: cnpg-cluster-app
                  key: password
