---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: client-secret
  namespace: tikal-backend
spec:
  encryptedData:
    secret: AgCKjlfFGBEeNaVeDIgdhD3bSjlQDS2jcwweZ2z7pfL8AblJSb2GhdzVL+nb81bdpCtMvbPzFr7Yo2GcdK41qj52WC8XoD+HNpUTYkceQRNsprECxZBd0jYbtDQIm82+U1XlEj5RvgV4EM4wVf+Gqg29TvGGF039GGDKbPozCeselAwR5Zg1R79i1khlU1ySpANAUaTirGLQ1YTSGvgo1Y6pskDVjQ3kAYWkYPS4g1OMTNVr8utvT5H2fJPtRJVHDBQCsQDrNYxUlFU9cYHeDVgFNI11NnXw+23u3qrLcqU+hrV4U0I4CimN9ab9NmdafG7Gpr6of4ycIkdYCuf3bRrgdbTzlIZGqKHqip8c1lH2XfAiRyUE3ByoWkb8X7u45252OYXYmnZXGeb7yRp6wa9CpTZhT0olLBE96YIeThb99Na0JEr8wuyVYqn3Co4dqZDLqMu42+wYJAuQMq+Fawjf1hBIK9dzhE2gpNkjBu8tI46Zy/FuDQ9bvGkEWiNPDOT6N+GcFJhA2Xg3M0UnAKXNNSbh3f0KFKsGnH5IHXLOsT/lxrBjRj7XH1X1axYhPWdyEZZO+tbiUC7sH/cDEPafP/S6AkGRX4El9gpbsOlGq0q7X83nyx6GfjzppEqGoAZ3+2c2Jdi6MVaIywOhssvdYRooxk8NbiD7Wjndyb3jDeInBeleBwTBPGlKEIVHLHlwsPd8wbiGrMWw4lvMP5evTbRAj1KT1Zce4TVxXvCWIcWh5C9rR1d1zd0VGQ==
  template:
    metadata:
      name: client-secret
      namespace: tikal-backend
