---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Enable Auto Merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    name: Enable auto merge 
    runs-on: ubuntu-24.04
    steps:
      - name: Enable Pull Request Automerge
        run: gh pr merge --merge --auto ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ secrets.AUTOMERGE_PAT }}